# Generated by Django 3.2.5 on 2021-07-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20210728_1939'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
