# Generated by Django 3.2.5 on 2021-07-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('recipe', '0002_auto_20210723_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='shopping_lists',
            field=models.ManyToManyField(to='users.ShoppingList'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shopping_lists',
            field=models.ManyToManyField(to='users.ShoppingList'),
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
