# Generated by Django 3.2.5 on 2021-07-28 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('recipe', '0004_recipe_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='shopping_lists',
            field=models.ManyToManyField(to='recipe.ShoppingList'),
        ),
    ]
