# Generated by Django 3.2.5 on 2021-07-29 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20210729_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='recipe_pics'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
