# Generated by Django 3.2.5 on 2021-08-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_alter_shoppinglist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='ingredient_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
