# Generated by Django 3.2.5 on 2021-08-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_auto_20210809_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure_unit',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
